insert into public.acesso(email) values ('brmilani@gmail.com') on conflict do nothing;
insert into public.marcas_config(marca, linhas) values
('JACQUES BOGART', '[["silver scent intense", "Silver Scent Intense"], ["infinite silver", "Infinite Silver"], ["infinity silver", "Infinite Silver"], ["silver scent aqua", "Silver Scent Aqua"], ["silver scent platinum", "Silver Scent Platinum"], ["silver scent midnight", "Silver Scent Midnight"], ["for her", "Silver Scent For Her"], ["silver scent", "Silver Scent"], ["one man show", "One Man Show"], ["bogart", "Silver Scent"]]'::jsonb),
('ULRIC DE VARENS', '[["for men", "For Men"], ["formen", "For Men"], ["chipre", "For Men"], ["blue", "Blue"], ["star", "Star"], ["flash", "Flash"], ["black", "Black"], ["night", "Night"], ["wild", "Wild"], ["gold", "Gold"], ["silver", "Silver"], ["absolu", "Absolu"], ["issime", "Issime"], ["sport", "Sport"], ["intense", "Intense"]]'::jsonb),
('CUBA PARIS', '[["la vida", "La Vida"], ["heartbreaker", "Heartbreaker"], ["gold", "Gold"], ["royal", "Royal"], ["black", "Black"], ["winner", "Winner"], ["prestige", "Prestige"], ["victory", "Victory"], ["classic", "Classic"], ["champs", "Champs"], ["strass", "Strass"], ["zebra", "Zebra"], ["magnum", "Magnum"], ["jungle", "Jungle"], ["copacabana", "Copacabana"], ["blue", "Blue"], ["red", "Red"], ["white", "White"], ["vip", "VIP"]]'::jsonb),
('ASSALA', '[["malik siba", "Malik Siba"], ["malik sahara", "Malik Sahara"], ["royal jasmine", "Royal Jasmine"], ["xtreme oud", "Xtreme Oud"], ["nasma", "Nasma"], ["divine", "Divine"], ["sunset", "Sunset"], ["sunrise", "Sunrise"], ["prime", "Prime"], ["oud", "Oud"], ["rose", "Rose"], ["musk", "Musk"], ["amber", "Amber"]]'::jsonb),
('ARMAF', '[["club de nuit intense man", "Club de Nuit Intense Man"], ["club de nuit intense woman", "Club de Nuit Intense Woman"], ["club de nuit urban elixir", "Club de Nuit Urban Elixir"], ["club de nuit urban man", "Club de Nuit Urban Man"], ["club de nuit blue iconic", "Club de Nuit Blue Iconic"], ["club de nuit imperiale", "Club de Nuit Imperiale"], ["club de nuit milestone", "Club de Nuit Milestone"], ["club de nuit sillage", "Club de Nuit Sillage"], ["club de nuit untold", "Club de Nuit Untold"], ["club de nuit iconic", "Club de Nuit Iconic"], ["club de nuit maleka", "Club de Nuit Maleka"], ["club de nuit woman", "Club de Nuit Intense Woman"], ["club de nuit white", "Club de Nuit White"], ["club de nuit intense", "Club de Nuit Intense Man"], ["club de nuit", "Club de Nuit Intense Man"], ["odyssey mandarin sky", "Odyssey Mandarin Sky"], ["odyssey white edition", "Odyssey White Edition"], ["odyssey lionheart", "Odyssey Lionheart"], ["odyssey tyrant", "Odyssey Tyrant"], ["odyssey homme", "Odyssey Homme"], ["odyssey aoud", "Odyssey Aoud"], ["odyssey", "Odyssey"], ["tag her", "Tag Her"], ["tag him", "Tag Him"], ["donna di terra", "Donna di Terra"], ["ventana", "Ventana"], ["tres nuit", "Tres Nuit"], ["derby", "Derby"], ["hunter", "Hunter"], ["sterling", "Sterling"], ["bucephalus", "Bucephalus"], ["voyage", "Voyage"], ["infinity", "Infinity"], ["overdose", "Overdose"], ["spectra", "Spectra"], ["yum", "Yum"]]'::jsonb),
('ANIMALE', '[["for men", "For Men"], ["for women", "For Women"], ["seduction", "Seduction"], ["black", "Black"], ["gold", "Gold"], ["love", "Love"], ["sexy", "Sexy"], ["homme", "Homme"], ["natural", "Natural"], ["tradicional", "For Men"]]'::jsonb)
on conflict (marca) do nothing;
